# Generated by Django 2.0.4 on 2018-04-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_widget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
